jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports:
          - 9092:9092
          - 9093:9093
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        depends_on:
          zookeeper:
            condition: service_healthy

    steps:
      - name: Wait for Kafka
        run: |
          docker run --network host confluentinc/cp-kafka:7.4.0 \
            kafka-topics --bootstrap-server localhost:9092 --list

      - name: Create topic
        run: |
          docker exec kafka kafka-topics --create \
            --bootstrap-server kafka:9092 \
            --topic notifications \
            --partitions 1 \
            --replication-factor 1
