name: CI Pipeline

env:
  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  REDIS_HOST: redis
  REDIS_PORT: 6379

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports:
          - 9092:9092
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Wait for Kafka to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 9092 && break || sleep 5;
          done

      - name: Create Kafka topics
        run: |
          docker exec $(docker ps --filter "name=kafka" --format "{{.ID}}") kafka-topics --create \
            --bootstrap-server localhost:9092 \
            --topic notifications \
            --partitions 1 \
            --replication-factor 1

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
