name: CI Pipeline

env:
  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  REDIS_HOST: redis
  REDIS_PORT: 6379

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports:
          - 9092:9092
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
          zookeeper:
            condition: service_healthy

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Wait for Kafka
        run: |
          for i in {1..10}; do
            docker exec kafka kafka-broker-api-versions --bootstrap-server kafka:9093 && break
            sleep 10
          done

      - name: Create Kafka topics
        run: |
          docker exec kafka kafka-topics --create \
            --bootstrap-server kafka:9093 \
            --topic notifications \
            --partitions 1 \
            --replication-factor 1

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
